#ifndef DBPROXIERCORE_GLOBAL_H
#define DBPROXIERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DBPROXIERCORE_LIBRARY)
#  define DBPROXIERCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define DBPROXIERCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DBPROXIERCORE_GLOBAL_H
